# Generated by Django 5.1.15 on 2026-09-11 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_seed_prendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleropa',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='No aplica a la distribución de ropa limpia, que se registra por prenda y cantidad.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='historicaldetalleropa',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='No aplica a la distribución de ropa limpia, que se registra por prenda y cantidad.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
