# Generated by Django 5.1.15 on 2026-09-10 15:54

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('NO_PELIGROSO', 'No peligroso'), ('RIESGO_BIOLOGICO', 'Riesgo biológico'), ('OTRO_PELIGROSO', 'Otro peligroso'), ('OTROS', 'Otros')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('color_bolsa', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='residuos.categoriaresiduo')),
            ],
            options={
                'verbose_name': 'categoría de residuo',
                'verbose_name_plural': 'categorías de residuo',
                'ordering': ['grupo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_bolsas', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria_residuo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='residuos.categoriaresiduo')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_residuo', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'detalle de residuo',
                'verbose_name_plural': 'detalles de residuo',
            },
        ),
        migrations.CreateModel(
            name='EntregaGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('kg_facturados', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_facturado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gestor_externo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.gestorexterno')),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega_gestor', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'entrega a gestor',
                'verbose_name_plural': 'entregas a gestor',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoriaResiduo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('NO_PELIGROSO', 'No peligroso'), ('RIESGO_BIOLOGICO', 'Riesgo biológico'), ('OTRO_PELIGROSO', 'Otro peligroso'), ('OTROS', 'Otros')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('color_bolsa', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria_padre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residuos.categoriaresiduo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical categoría de residuo',
                'verbose_name_plural': 'historical categorías de residuo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDetalleResiduo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_bolsas', models.PositiveIntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria_residuo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residuos.categoriaresiduo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'historical detalle de residuo',
                'verbose_name_plural': 'historical detalles de residuo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEntregaGestor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('kg_facturados', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_facturado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('gestor_externo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.gestorexterno')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'historical entrega a gestor',
                'verbose_name_plural': 'historical entregas a gestor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='categoriaresiduo',
            constraint=models.UniqueConstraint(fields=('categoria_padre', 'nombre'), name='unique_categoria_por_padre'),
        ),
        migrations.AddConstraint(
            model_name='detalleresiduo',
            constraint=models.UniqueConstraint(fields=('movimiento', 'categoria_residuo'), name='unique_categoria_por_movimiento'),
        ),
    ]
