# Generated by Django 5.1.15 on 2026-09-21 12:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0005_categorias_y_columnas_rh1_oficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleresiduo',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='historicaldetalleresiduo',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
