# Generated by Django 5.1.15 on 2026-09-10 15:54

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('movimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('disposicion', models.CharField(choices=[('TULA_ROJA', 'Tula roja'), ('CANECA_ROJA', 'Caneca roja')], max_length=15)),
                ('controla_unidades', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'prenda',
                'verbose_name_plural': 'prendas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrenda',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('disposicion', models.CharField(choices=[('TULA_ROJA', 'Tula roja'), ('CANECA_ROJA', 'Caneca roja')], max_length=15)),
                ('controla_unidades', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical prenda',
                'verbose_name_plural': 'historical prendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRotulo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_rotulo', models.CharField(blank=True, max_length=50)),
                ('contenido', models.TextField(blank=True)),
                ('rotulada', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area_servicio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.areaservicio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'historical rótulo',
                'verbose_name_plural': 'historical rótulos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDetalleRopa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad_unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
                ('prenda', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ropa.prenda')),
            ],
            options={
                'verbose_name': 'historical detalle de ropa',
                'verbose_name_plural': 'historical detalles de ropa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rotulo', models.CharField(blank=True, max_length=50)),
                ('contenido', models.TextField(blank=True)),
                ('rotulada', models.BooleanField(default=True)),
                ('area_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotulos', to='core.areaservicio')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotulos', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'rótulo',
                'verbose_name_plural': 'rótulos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.PositiveIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ropa', to='movimientos.movimiento')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='ropa.prenda')),
            ],
            options={
                'verbose_name': 'detalle de ropa',
                'verbose_name_plural': 'detalles de ropa',
                'constraints': [models.UniqueConstraint(fields=('movimiento', 'prenda'), name='unique_prenda_por_movimiento')],
            },
        ),
    ]
