# Generated by Django 5.1.15 on 2026-09-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0004_prendas_imagenes_ambulancia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotulo',
            options={'ordering': ['-id'], 'verbose_name': 'rótulo', 'verbose_name_plural': 'rótulos'},
        ),
    ]
