# Generated by Django 5.1.15 on 2026-09-10 15:54

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfiguracionJornada',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('proceso', models.CharField(choices=[('ROPA', 'Ropa'), ('RESIDUOS', 'Residuos')], max_length=10)),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sede')),
            ],
            options={
                'verbose_name': 'historical configuración de jornada',
                'verbose_name_plural': 'historical configuraciones de jornada',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ROPA_SUCIA_ENTREGA', 'Entrega de ropa sucia'), ('ROPA_LIMPIA_RECEPCION', 'Recepción de ropa limpia'), ('ROPA_LIMPIA_DISTRIBUCION', 'Distribución de ropa limpia'), ('RESIDUO_GENERACION', 'Generación de residuos'), ('RESIDUO_RECOLECCION', 'Recolección de residuos')], max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], editable=False, max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_CARGA', 'Pendiente de carga'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('periodo_facturacion', models.DateField(help_text='Primer día del mes de facturación; puede diferir del mes de la fecha.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('area_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.areaservicio')),
                ('creado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('entrega_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entregados', to=settings.AUTH_USER_MODEL)),
                ('mov_origen', models.ForeignKey(blank=True, help_text='Enlaza la recepción de ropa limpia con la entrega de ropa sucia que le dio origen (ciclo de retorno, 6.3).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_resultantes', to='movimientos.movimiento')),
                ('recibe_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.sede')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'movimientos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPesaje',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tara', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pesado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'historical pesaje',
                'verbose_name_plural': 'historical pesajes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNovedad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('FALTANTE', 'Faltante de prendas'), ('SOBRANTE', 'Sobrante'), ('ROPA_ROTA', 'Ropa rota'), ('ROPA_MANCHADA', 'Ropa manchada'), ('ROPA_DETERIORADA', 'Ropa deteriorada'), ('ROPA_PENDIENTE_DEVOLUCION', 'Ropa pendiente de devolución'), ('PERDIDA_PRENDAS', 'Pérdida de prendas'), ('ROPA_SIN_ROTULAR', 'Ropa sin rotular'), ('BOLSA_INADECUADA', 'Bolsa o recipiente inadecuado'), ('DERRAME', 'Derrame'), ('RESIDUO_SIN_IDENTIFICAR', 'Residuo sin identificar'), ('REGISTRO_PENDIENTE', 'Registro pendiente'), ('DANO_RECIPIENTE', 'Daño del recipiente'), ('DIFERENCIA_PESO', 'Diferencia de peso'), ('OTRA', 'Otra')], max_length=30)),
                ('cantidad_afectada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacion', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'historical novedad',
                'verbose_name_plural': 'historical novedades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovimiento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ROPA_SUCIA_ENTREGA', 'Entrega de ropa sucia'), ('ROPA_LIMPIA_RECEPCION', 'Recepción de ropa limpia'), ('ROPA_LIMPIA_DISTRIBUCION', 'Distribución de ropa limpia'), ('RESIDUO_GENERACION', 'Generación de residuos'), ('RESIDUO_RECOLECCION', 'Recolección de residuos')], max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], editable=False, max_length=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_CARGA', 'Pendiente de carga'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('periodo_facturacion', models.DateField(help_text='Primer día del mes de facturación; puede diferir del mes de la fecha.')),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.areaservicio')),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entrega_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recibe_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sede')),
                ('mov_origen', models.ForeignKey(blank=True, db_constraint=False, help_text='Enlaza la recepción de ropa limpia con la entrega de ropa sucia que le dio origen (ciclo de retorno, 6.3).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'historical movimiento',
                'verbose_name_plural': 'historical movimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('FALTANTE', 'Faltante de prendas'), ('SOBRANTE', 'Sobrante'), ('ROPA_ROTA', 'Ropa rota'), ('ROPA_MANCHADA', 'Ropa manchada'), ('ROPA_DETERIORADA', 'Ropa deteriorada'), ('ROPA_PENDIENTE_DEVOLUCION', 'Ropa pendiente de devolución'), ('PERDIDA_PRENDAS', 'Pérdida de prendas'), ('ROPA_SIN_ROTULAR', 'Ropa sin rotular'), ('BOLSA_INADECUADA', 'Bolsa o recipiente inadecuado'), ('DERRAME', 'Derrame'), ('RESIDUO_SIN_IDENTIFICAR', 'Residuo sin identificar'), ('REGISTRO_PENDIENTE', 'Registro pendiente'), ('DANO_RECIPIENTE', 'Daño del recipiente'), ('DIFERENCIA_PESO', 'Diferencia de peso'), ('OTRA', 'Otra')], max_length=30)),
                ('cantidad_afectada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacion', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='movimientos.movimiento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('tara', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_neto', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesajes', to='movimientos.movimiento')),
                ('pesado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pesaje',
                'verbose_name_plural': 'pesajes',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(choices=[('ROPA', 'Ropa'), ('RESIDUOS', 'Residuos')], max_length=10)),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_jornadas', to='core.sede')),
            ],
            options={
                'verbose_name': 'configuración de jornada',
                'verbose_name_plural': 'configuraciones de jornada',
                'ordering': ['sede__nombre', 'proceso', 'jornada'],
                'constraints': [models.UniqueConstraint(fields=('sede', 'proceso', 'jornada'), name='unique_config_jornada')],
            },
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha', 'jornada'], name='movimientos_fecha_527d81_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['sede', 'area_origen', 'fecha'], name='movimientos_sede_id_01efb8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo_movimiento', 'fecha'], name='movimientos_tipo_mo_48e13d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['periodo_facturacion'], name='movimientos_periodo_a94ede_idx'),
        ),
        migrations.AddConstraint(
            model_name='pesaje',
            constraint=models.CheckConstraint(condition=models.Q(('tara__lte', models.F('peso_total'))), name='tara_no_mayor_a_peso_total'),
        ),
        migrations.AddConstraint(
            model_name='pesaje',
            constraint=models.CheckConstraint(condition=models.Q(('peso_total__gte', 0), ('tara__gte', 0)), name='pesos_no_negativos'),
        ),
    ]
