# Generated by Django 5.1.15 on 2026-09-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimiento',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
