# Generated by Django 5.1.15 on 2026-09-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupos_y_permisos'),
        ('movimientos', '0002_movimiento_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='area_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Servicio generador. No aplica a la recepción de ropa limpia, que viene de lavandería.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.areaservicio'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='area_origen',
            field=models.ForeignKey(blank=True, help_text='Servicio generador. No aplica a la recepción de ropa limpia, que viene de lavandería.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='core.areaservicio'),
        ),
    ]
