# Generated by Django 5.1.15 on 2026-09-10 20:59

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grupos_y_permisos'),
        ('movimientos', '0003_area_origen_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalValidacionEntrega',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10)),
                ('peso_declarado', models.DecimalField(decimal_places=2, help_text='Total en kg que el personal contó a mano para la jornada.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacion', models.TextField(blank=True)),
                ('validado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sede')),
                ('validado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical validación de entrega',
                'verbose_name_plural': 'historical validaciones de entrega',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ValidacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jornada', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10)),
                ('peso_declarado', models.DecimalField(decimal_places=2, help_text='Total en kg que el personal contó a mano para la jornada.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacion', models.TextField(blank=True)),
                ('validado_en', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones', to='core.sede')),
                ('validado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validación de entrega',
                'verbose_name_plural': 'validaciones de entrega',
                'ordering': ['-fecha', 'sede__nombre', 'jornada'],
                'constraints': [models.UniqueConstraint(fields=('sede', 'fecha', 'jornada'), name='unique_validacion_jornada')],
            },
        ),
    ]
