# Generated by Django 5.1.15 on 2026-09-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_validacion_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpesaje',
            name='cantidad_bolsas',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de bolsas o tulas, cuando se controle este dato (RF-009).', null=True),
        ),
        migrations.AddField(
            model_name='pesaje',
            name='cantidad_bolsas',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de bolsas o tulas, cuando se controle este dato (RF-009).', null=True),
        ),
    ]
