# Generated by Django 5.1.15 on 2026-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_pesaje_cantidad_bolsas'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovimiento',
            name='firma_entrega',
            field=models.TextField(blank=True, help_text='Firma dibujada en pantalla de quien entrega, cuando no es quien inició sesión (imagen PNG en base64).'),
        ),
        migrations.AddField(
            model_name='historicalmovimiento',
            name='firma_recibe',
            field=models.TextField(blank=True, help_text='Firma dibujada en pantalla de quien recibe, cuando no es quien inició sesión (imagen PNG en base64).'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='firma_entrega',
            field=models.TextField(blank=True, help_text='Firma dibujada en pantalla de quien entrega, cuando no es quien inició sesión (imagen PNG en base64).'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='firma_recibe',
            field=models.TextField(blank=True, help_text='Firma dibujada en pantalla de quien recibe, cuando no es quien inició sesión (imagen PNG en base64).'),
        ),
    ]
