# Generated by Django 5.1.15 on 2026-09-10 21:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0002_seed_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaRH1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(help_text='Encabezado de la columna en el RH1.', max_length=150)),
                ('grupo', models.CharField(blank=True, choices=[('NO_PELIGROSO', 'No peligroso'), ('RIESGO_BIOLOGICO', 'Riesgo biológico'), ('OTRO_PELIGROSO', 'Otro peligroso'), ('OTROS', 'Otros')], help_text='Suma todo un grupo. Dejar vacío si se listan categorías específicas.', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, help_text='Categorías específicas que suma esta columna.', related_name='columnas_rh1', to='residuos.categoriaresiduo')),
            ],
            options={
                'verbose_name': 'columna del RH1',
                'verbose_name_plural': 'columnas del RH1',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalColumnaRH1',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(help_text='Encabezado de la columna en el RH1.', max_length=150)),
                ('grupo', models.CharField(blank=True, choices=[('NO_PELIGROSO', 'No peligroso'), ('RIESGO_BIOLOGICO', 'Riesgo biológico'), ('OTRO_PELIGROSO', 'Otro peligroso'), ('OTROS', 'Otros')], help_text='Suma todo un grupo. Dejar vacío si se listan categorías específicas.', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical columna del RH1',
                'verbose_name_plural': 'historical columnas del RH1',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalColumnaRH1_categorias',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoriaresiduo', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residuos.categoriaresiduo')),
                ('columnarh1', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='residuos.columnarh1')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='residuos.historicalcolumnarh1')),
            ],
            options={
                'verbose_name': 'HistoricalColumnaRH1_categorias',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
