# Generated by Django 5.1.15 on 2026-09-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicios_centro_y_clinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administradora'), ('USUARIO', 'Usuario'), ('SERVICIO', 'Personal de servicio')], default='USUARIO', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administradora'), ('USUARIO', 'Usuario'), ('SERVICIO', 'Personal de servicio')], default='USUARIO', max_length=10),
        ),
    ]
